name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  skip-init:
    runs-on: macos-13
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create New Skip Package (Debug)
        run: |
          mkdir SomeLibraryDebug
          cd SomeLibraryDebug
          swift package init

          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skip", branch: "main")]' >> Package.swift
          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skiphub", branch: "main")]' >> Package.swift

          swift package plugin --allow-writing-to-package-directory skip-init
          cat Package.swift Package.resolved
          swift build --jobs 1 --configuration debug
          swift test --jobs 1 --configuration debug
          brew install tree || true
          tree -l -I build
          cd -

      - name: Create New Skip Package (Release)
        run: |
          mkdir SomeLibraryRelease
          cd SomeLibraryRelease
          swift package init

          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skip", from: "0.0.0")]' >> Package.swift
          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skiphub", from: "0.0.0")]' >> Package.swift

          swift package plugin --allow-writing-to-package-directory skip-init
          cat Package.swift Package.resolved
          swift build --jobs 1 --configuration release
          swift test --jobs 1 --configuration release
          brew install tree || true
          tree -l -I build
          cd -

