name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  pull_request:
jobs:
  skip-ci:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-15', 'ubuntu-24.04']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          add-job-summary: never

      - name: Checkout skipstone
        uses: actions/checkout@v4
        with:
          repository: skiptools/skipstone
          path: skipstone
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Checkout skip
        uses: actions/checkout@v4
        with:
          repository: skiptools/skip
          path: skip
          # need to fetch tags so we know the most recent version
          fetch-tags: true

      - name: Setup Xcode
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          # workaround for missing iPhone 16 simulator:
          # https://github.com/actions/runner-images/issues/12758#issuecomment-3187301409
          sudo xcode-select --switch /Applications/Xcode_16.4.app

      - name: Setup SKIPLOCAL
        run: |
          echo "SKIPLOCAL=$PWD/skipstone" >> $GITHUB_ENV
          echo "PATH=$PWD/skip/.build/plugins/tools/debug:$PWD/skip/.build/debug:$PATH" >> $GITHUB_ENV

      - name: Build Skip
        working-directory: skip
        run: swift build

      - name: Test Skip
        # TODO: fix tests on Linux
        if: ${{ startsWith(matrix.os, 'macos-') }}
        working-directory: skip
        run: swift test


