name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  skip-init:
    runs-on: macos-13
    steps:
      - name: Checkout skip
        uses: actions/checkout@v3

      - name: Test Skip
        run: swift test

      - name: Run skip doctor
        run: swift run skip doctor

      - name: Test Homebrew Tap
        run: |
          brew install skiptools/skip/skip
          skip version

      - name: Test Mint Install
        run: |
          brew install mint
          mint run skiptools/skip version

