name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  skip-init:
    runs-on: macos-13
    steps:
      - run: brew install skiptools/skip/skip

      - name: Checkout skip
        uses: actions/checkout@v3

      - name: Test Skip
        run: swift test

      - name: Run skip doctor
        run: skip doctor --plain

      - name: Run skip init
        run: skip init --plain --build --test -d `mktemp -d` skppkg Mod1 Mod2

      - name: Run skip create
        if: false
        run: skip create --plain --build --test -d `mktemp -d` skpapp

