name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

#env:
#  DEVELOPER_DIR: /Applications/Xcode_16.2.app

jobs:
  skip-ci:
    runs-on: macos-15
    steps:
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          add-job-summary: never

      - name: Checkout skipstone
        uses: actions/checkout@v4
        with:
          repository: skiptools/skipstone
          path: skipstone
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Checkout skip
        uses: actions/checkout@v4
        with:
          repository: skiptools/skip
          path: skip

      - name: Setup SKIPLOCAL
        run: |
          echo "SKIPLOCAL=$PWD/skipstone" >> $GITHUB_ENV
          echo "PATH=$PWD/skip/.build/plugins/tools/debug:$PWD/skip/.build/debug:$PATH" >> $GITHUB_ENV

      - name: Build Skip
        working-directory: skip
        run: swift build

      - name: Test Skip
        working-directory: skip
        run: swift test


