name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3,9,15,21 * * *'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  skip-init:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - name: Create New Skip Package (Release)
        run: |
          mkdir SomeLibrary
          cd SomeLibrary
          swift package init

          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skip", from: "0.0.0")]' >> Package.swift
          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skiphub", from: "0.0.0")]' >> Package.swift

          swift package plugin --allow-writing-to-package-directory skip-init
          cat Package.swift Package.resolved
          swift test -j 1 --configuration release
          brew install tree || true
          tree -l -I build

      - name: Create New Skip Package (Debug)
        run: |
          mkdir SomeOtherLibrary
          cd SomeOtherLibrary
          swift package init

          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skip", branch: "main")]' >> Package.swift
          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skiphub", branch: "main")]' >> Package.swift

          swift package plugin --allow-writing-to-package-directory skip-init
          cat Package.swift Package.resolved
          swift test -j 1 --configuration debug
          brew install tree || true
          tree -l -I build

