name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

jobs:
  skip-init:
    runs-on: macos-14
    steps:
      - name: Checkout skip
        uses: actions/checkout@v4

      - name: Test Skip
        run: swift test

