name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

#env:
#  DEVELOPER_DIR: /Applications/Xcode_16.2.app

jobs:
  skip-init:
    runs-on: macos-15
    steps:
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          add-job-summary: never

      - name: Checkout skipstone
        uses: actions/checkout@v4
        with:
          repository: skiptools/skipstone
          path: skipstone
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Checkout skip
        uses: actions/checkout@v4
        with:
          repository: skiptools/skip
          path: skip

      - name: Swift Test
        working-directory: skip
        #run: SKIPLOCAL=${PWD}/../skipstone swift test
        #run: brew install skiptools/skip/skip && swift test
        # running locally against skipstone checkout broken as of
        run: PATH=$PWD/.build/plugins/tools/debug:$PATH SKIPLOCAL=${PWD}/../skipstone swift test


