name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3,9,15,21 * * *'

jobs:
  skip-init:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - name: Create New Skip Package
        run: |
          mkdir SomeLibrary
          cd SomeLibrary

          swift package init 

          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skip", from: "0.0.0")]' >> Package.swift
          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skiphub", from: "0.0.0")]' >> Package.swift

          swift package plugin --allow-writing-to-package-directory skip-init

          # the artifact tool should be downloaded locally
          ./.build/artifacts/skip/skiptool.artifactbundle/skiptool version

          cat Package.swift Package.resolved
          
          xcodebuild test -skipPackagePluginValidation -sdk "macosx" -destination "platform=macosx" -scheme SomeLibrary-Package

          # add in an assertion failure to ensure the test now fails
          echo 'extension SomeLibraryTests { func testFailure() { XCTAssertEqual(1, 2) } }' >> Tests/SomeLibraryTests/SomeLibraryTests.swift

          xcodebuild test -skipPackagePluginValidation -sdk "macosx" -destination "platform=macosx" -scheme SomeLibrary-Package && false || true

          brew install tree || true
          tree -l -I build

