name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    # run at 9AM & 9PM UTC
    - cron:  '0 9,21 * * *'

jobs:
  tool:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - name: Check Tool
        run: |
          mkdir /tmp/ExampleSkipProject
          cd /tmp/ExampleSkipProject
          swift package init
          swift test
          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skip.git", from: "0.0.0")]' >> Package.swift

          # the failure seems to not affect the swift package command, though…
          swift package --disable-sandbox --allow-writing-to-package-directory skip version

          # also try to run the tool directly from the cache
          ./.build/artifacts/skip/skiptool.artifactbundle/skiptool version

  skip-init:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - name: Create New Skip Package
        run: |
          swift package init --type library --name SomeLibrary
          cat Package.swift
          swift test

          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skip.git", from: "0.0.0")]' >> Package.swift
          swift package --allow-writing-to-package-directory skip version

          echo 'package.dependencies += [.package(url: "https://github.com/skiptools/skiphub.git", from: "0.0.0")]' >> Package.swift
          swift package --allow-writing-to-package-directory skip version
          echo "Creating scaffold" 
          swift package plugin --allow-writing-to-package-directory skip-init

          cat Package.swift
          
          xcodebuild test -skipPackagePluginValidation -sdk "macosx" -destination "platform=macosx" -scheme SomeLibrary-Package

          # add in a failure and ensure the test now fails
          echo 'extension SomeLibraryTests { func testFailure() { XCTAssertEqual(1, 2) } }' >> Tests/SomeLibraryTests/SomeLibraryTests.swift

          xcodebuild test -skipPackagePluginValidation -sdk "macosx" -destination "platform=macosx" -scheme SomeLibrary-Package && false || true


