name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_16.3.app/Contents/Developer

jobs:
  skip-init:
    runs-on: macos-15
    steps:
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          add-job-summary: never

      - name: Checkout skipstone
        uses: actions/checkout@v4
        with:
          repository: skiptools/skipstone
          path: skipstone
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Checkout skip
        uses: actions/checkout@v4
        with:
          repository: skiptools/skip
          path: skip

      - name: Swift Test
        working-directory: skip
        run: SKIPLOCAL=${PWD}/../skipstone swift test


