name: skip ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  skip-init:
    runs-on: macos-13
    steps:
      - name: Checkout skip
        uses: actions/checkout@v3
        with:
          path: skip
          repository: skiptools/skip

      - name: Test Skip
        working-directory: skip
        run: swift test

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create New Skip Package (Debug)
        run: |
          mkdir SomeLibraryDebug
          cd SomeLibraryDebug
          swift package init

          echo 'package.platforms = package.platforms ?? [.macOS("13"), .iOS("16")]' >> Package.swift
          echo 'package.dependencies += [.package(url: "https://skip.tools/skiptools/skip.git", branch: "main")]' >> Package.swift
          echo 'package.dependencies += [.package(url: "https://skip.tools/skiptools/skiphub.git", branch: "main")]' >> Package.swift

          swift package plugin --allow-writing-to-package-directory skip-init
          cat Package.swift Package.resolved

      - name: Build Skip Package (Debug)
        working-directory: SomeLibraryDebug
        run: |
          swift build --jobs 1 --configuration debug

      - name: Test Skip Package (Debug)
        working-directory: SomeLibraryDebug
        run: |
          swift test --jobs 1 --configuration debug

      - name: Test Homebrew Tap
        run: |
          brew install skiptools/skip/skip
          skip version

      - name: Test Mint Install
        run: |
          brew install mint
          mint run skiptools/skip version

      - name: Show Skip Package (Debug)
        # disabled for concurrency
        if: false
        working-directory: SomeLibraryDebug
        run: |
          brew install tree || true
          tree -l -I build
          cd -

      - name: Create New Skip Package (Release)
        # disables for concurrency
        if: false
        run: |
          mkdir SomeLibraryRelease
          cd SomeLibraryRelease
          swift package init

          echo 'package.dependencies += [.package(url: "https://skip.tools/skiptools/skip.git", from: "0.0.0")]' >> Package.swift
          echo 'package.dependencies += [.package(url: "https://skip.tools/skiptools/skiphub.git", from: "0.0.0")]' >> Package.swift

          swift package plugin --allow-writing-to-package-directory skip-init
          cat Package.swift Package.resolved
          swift build --jobs 1 --configuration release
          swift test --jobs 1 --configuration release
          brew install tree || true
          tree -l -I build
          cd -


