name: skip checks

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  skip-init:
    runs-on: macos-14
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
    steps:
      - run: brew install skiptools/skip/skip
      - run: skip checkup --verbose --double-check

