name: "skipapp"
on:
  workflow_call:
jobs:
  skipapp:
    runs-on: macos-13
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "APP_VERSION=${TAG:-'0.0.0'}" > $GITHUB_ENV
          echo "COMMIT_DATE=$(git log -1 --format=%ad --date=iso-strict ${GITHUB_REF#refs/tags/})" > $GITHUB_ENV
          sed -i '' "s;MARKETING_VERSION = .*;MARKETING_VERSION = $(git describe --tags --abbrev=0 --match '[0-9]*\.[0-9]*\.[0-9]*' --first-parent);g" App.xcconfig
          sed -i '' "s;PRODUCT_VERSION = .*;PRODUCT_VERSION = $(git rev-list --count HEAD);g" App.xcconfig

      - name: Run Tests
        run: swift test

      - name: Build ipa
        run: |
          mkdir -p Packages/Skip/artifacts
          APPARTIFACT="App"
          for CONFIGURATION in "Debug" "Release"; do
            ARCHIVE_PATH=".build/Skip/artifacts/${CONFIGURATION}/${APPARTIFACT}.xcarchive"
            BUILT_PRODUCTS_DIR=".build" xcodebuild -derivedDataPath .build/DerivedData -skipPackagePluginValidation -archivePath "${ARCHIVE_PATH}" -configuration "${CONFIGURATION}" -scheme "App" -sdk "iphoneos" -destination "generic/platform=iOS" -jobs 1 archive CODE_SIGNING_ALLOWED=NO
            cd "${ARCHIVE_PATH}"/Products/
            find . -type f
            mv "Applications" "Payload"
            # create zip file with reproducible timestamps
            find "Payload" -exec touch -t 197001010000 {} \;
            zip -9 -r "${APPARTIFACT}-${CONFIGURATION}.ipa" "Payload"

            cd -
            cp -av "${ARCHIVE_PATH}/Products/${APPARTIFACT}-${CONFIGURATION}.ipa" Packages/Skip/artifacts/
          done

      - name: Build apk
        run: |
          for CONFIGURATION in "Release" "Debug"; do
            # for some reason we need to build twice
            for X in "A" "B"; do 
              BUILT_PRODUCTS_DIR=".build" xcodebuild -derivedDataPath .build/DerivedData -skipPackagePluginValidation -configuration "${CONFIGURATION}" -destination "platform=macosx" -scheme "AppDroid" build
            done
          done

      - name: Assemble Swift Source
        run: |
          # create the source zip file with predictable timestamps for reproducibility
          find . -exec touch -d "${COMMIT_DATE:0:19}" {} \;
          mkdir -p Packages/Skip/artifacts/
          zip -9 -r "Packages/Skip/artifacts/App-Source.zip" . -x "Packages/*" -x ".git/*" -x ".build/*" -x ".*/*"

      - name: Assemble Kotlin Source
        run: |
          cd .build/DerivedData/SourcePackages/plugins/*.output/AppUIKt/skip-transpiler/
          rm -rf .gradle .build */.build
          # create the zip file with predictable timestamps for reproducibility
          find . -exec touch -d "${COMMIT_DATE:0:19}" {} \;
          zip -9 -r "${OLDPWD}/Packages/Skip/artifacts/App-android-source.zip" . -x ".build/*" -x "*/.gradle/*" -x "*/.build/*" -x "*/build/*"
          cd -

      - name: Merge Artifacts
        run: |
          # merge the ipa and apk zips into a single archive
          cd Packages/Skip/artifacts/
          ls -la

          APPNAME="App"
          IPA="${APPNAME}-Release.ipa"
          APK="${APPNAME}UI-release.apk"
          APPZ="${APPNAME}.appz"

          TMPDIR=$(mktemp -d)
          unzip -q "$IPA" -d "$TMPDIR"
          cp "${APK}" "${TMPDIR}/.source.apk"
          cd "${TMPDIR}"
          zip -qr9 ".source.apk" ./*
          cd -
          mv "${TMPDIR}/.source.apk" "${APPZ}"
          shasum -a 256 ${APK} ${IPA} ${APPZ}
          ls -lah ${APK} ${IPA} ${APPZ}

      - name: "Release"
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Creating release: ${TAG}"
          cd Packages/Skip/artifacts/

          ls -la 

          APPNAME="App"

          # TODO: check whether this is a template project
          cp -v ${APPNAME}-Source.zip skip-template-source.zip

          # fix artifact names for release (retain App-Source.zip for template)
          mv -v ${APPNAME}-Source.zip ${APPNAME}-ios-${TAG}-source.zip
          mv -v ${APPNAME}UI-release.apk ${APPNAME}-android-${TAG}.apk
          #mv -v ${APPNAME}UI-debug.apk ${APPNAME}-android-${TAG}-debug.apk
          mv -v ${APPNAME}-Release.ipa ${APPNAME}-ios-${TAG}.ipa
          #mv -v ${APPNAME}-Debug.ipa ${APPNAME}-ios-${TAG}-debug.ipa
          mv -v ${APPNAME}-android-source.zip ${APPNAME}-android-${TAG}-source.zip
          mv -v ${APPNAME}.appz ${APPNAME}-${TAG}.appz

          shasum -a 256 *.* > checksums.txt

          cat > .relnotes << EOF
          These are the checksums for the release artifacts:
          EOF
          echo '```' >> .relnotes
          cat checksums.txt >> .relnotes
          echo '```' >> .relnotes

          #gh release create "${TAG}" -t "Release ${TAG}" -F .relnotes *.*
          # manually create the release to control the order
          gh release create "${TAG}" -t "Release ${TAG}" -F .relnotes \
            ${APPNAME}-ios-${TAG}.ipa \
            ${APPNAME}-ios-${TAG}-source.zip \
            ${APPNAME}-android-${TAG}.apk \
            ${APPNAME}-android-${TAG}-source.zip \
            ${APPNAME}-${TAG}.appz \
            skip-template-source.zip \
            checksums.txt

      - name: "Upload Build Artifacts"
        # upload the artifacts generated from each build
        uses: actions/upload-artifact@v3
        if: always()
        with: 
          path: Packages/Skip/artifacts/

