name: skip checks

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  skip-init:
    runs-on: macos-15
    steps:
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          add-job-summary: never
      - name: Cache Homebrew packages
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew
          key: homebrew-packages

      - run: brew install skiptools/skip/skip
      - run: skip checkup
      #- run: skip checkup --verbose --double-check
      - run: skip init demo-module DemoModule
      - run: skip init --appid=xyz.skip.Demo demo-app DemoApp DemoModule
      - run: skip init --appfair DemoFairApp

      - run: skip android sdk install --verbose
      - run: skip checkup --verbose --native
      - run: skip init --native demo-module-native DemoModule
      - run: skip init --native --kotlincompat demo-module-kotlincompat DemoModule
      - run: skip init --native --appid=xyz.skip.Demo demo-app-native DemoApp DemoModule

