name: skip checks

on:
  workflow_call:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  skip-init:
    runs-on: macos-13
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - run: brew install skiptools/skip/skip
      - run: skip doctor
      - run: skip checkup
      - run: skip lib init --build --test -d $(mktemp -d) skppkg Mod1 Mod2
      - run: skip app init --build --test -d $(mktemp -d) skpapp
      - run: skip app init --template skipapp-weather --build --test -d $(mktemp -d) skpapp
      #- run: skip app init --template skipapp-playground --build --test -d $(mktemp -d) skpapp
      #- run: skip app init --template skipapp-hello --build --test -d $(mktemp -d) skpapp

