name: skip checks

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  skip-init:
    runs-on: macos-13
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - run: brew install skiptools/skip/skip
      - run: skip checkup --double-check
      - run: brew install openjdk@21
      - run: brew upgrade gradle
      - run: skip checkup --double-check

