name: skip checks

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  skip-init:
    runs-on: macos-13
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - run: brew install skiptools/skip/skip
      - run: skip doctor
      - run: skip checkup
      - run: skip lib init --build --test -d $(mktemp -d) skppkg Mod1
      #- run: skip lib init --build --test -d $(mktemp -d) skppkg Mod1 Mod2
      - run: skip lib init -c debug --build --test --version=1.0.0 --appid=world.Hello --ipa --apk -d $(mktemp -d) hello-world Hello:skip-ui/SkipUI
      - run: skip lib init -c debug --build --no-test --version=1.0.1 --appid=world.Hello --ipa --apk --chain -d $(mktemp -d) hello-world Hello:skip-ui/SkipUI HelloModel:skip-model/SkipModel:skip-foundation/SkipFoundation
      - run: skip lib init -c release --build --no-test --version=1.0.2 --appid=world.Hello --ipa --apk -d $(mktemp -d) hello-world Hello:skip-ui/SkipUI

      #- run: skip app create --build --test -d $(mktemp -d) skpapp
      #- run: skip app create --template skipapp-weather --build --test -d $(mktemp -d) skpapp
      #- run: skip app create --template skipapp-playground --build --test -d $(mktemp -d) skpapp
      #- run: skip app create --template skipapp-hello --build --test -d $(mktemp -d) skpapp

