name: skip checks

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  skip-init:
    runs-on: macos-15
    steps:
      # cache gradle/maven dependencies which speeds up skip checkup
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          generate-job-summary: false
      - run: brew install skiptools/skip/skip
      - run: skip checkup --verbose --double-check
      - run: skip android sdk install
      - run: skip checkup --verbose --native

