name: skip distribution checks

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  skip-init:
    runs-on: macos-13
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - run: brew install skiptools/skip/skip
      - run: skip doctor --plain
      - run: skip checkup --plain
      - run: skip init --plain --build --test -d `mktemp -d` skppkg Mod1 Mod2
      - run: skip create --plain --build --test -d `mktemp -d` skpapp
      - run: skip create --template skipapp-weather --plain --build --test -d `mktemp -d` skpapp
      #- run: skip create --template skipapp-playground --plain --build --test -d `mktemp -d` skpapp

