name: "skiplib"
on:
  workflow_call:
jobs:
  skiplib:
    runs-on: macos-13
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test
      - name: Assemble
        run: |
          brew install skiptools/skip/skip
          skip doctor
          #skip assemble -o Packages/Skip/artifacts/skip-unit-0.0.0.aar SkipUnit
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # extract package and initial module name from Package.swift
          PACKAGE=$(swift package dump-package | jq -r '.name')
          MODULE=$(swift package dump-package | jq -r '.targets[0].name')
          COMMIT_DATE=$(git log -1 --format=%ad --date=iso-strict ${GITHUB_REF#refs/tags/})

          # the tag is the most recent GitHub ref
          TAG="${GITHUB_REF#refs/tags/}"

          gradle assemble --project-dir Packages/Skip/${PACKAGE}/${MODULE}KtTests/skip-transpiler -PbuildDir=.build/${MODULE}

          echo "Creating release: ${TAG}"
          mkdir -p Packages/Skip/artifacts/
          PKGDIR="../../../../../../Packages/Skip/artifacts/"
          # create the release .aar
          cd ./.build/plugins/outputs/${PACKAGE}/${MODULE}KtTests/skip-transpiler
          cp -a ${MODULE}/.build/${MODULE}/outputs/aar/${MODULE}-release.aar ${PKGDIR}/${PACKAGE}-${TAG}.aar
          # copy the license for the source jar
          cp ../../../../../../LICENSE* .

          # create a source .jar distribution with consistent timestamps
          find . -exec touch -d "${COMMIT_DATE:0:19}" {} \;

          zip -r ${PKGDIR}/${PACKAGE}-${TAG}-sources.jar . -x '.*' -x '.*/*' -x '*/.*/*'

          # create a release with the assets and a checksums.txt file
          cd ${PKGDIR}
          shasum -a 256 *.* > checksums.txt
          echo 'Release artifact SHA-256 hashes:' >> .relnotes
          echo '```' >> .relnotes
          cat checksums.txt >> .relnotes
          echo '```' >> .relnotes
          gh release create "${TAG}" -t "Release ${TAG}" -F .relnotes *.*

