name: skip checks

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  skip-init:
    runs-on: macos-14
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: release-candidate
      - run: brew install skiptools/skip/skip
      - run: skip checkup --verbose --double-check

