name: "skipapp"
on:
  workflow_call:
jobs:
  skipapp:
    runs-on: macos-13
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "APP_VERSION=${TAG:-'0.0.0'}" > $GITHUB_ENV
          echo "COMMIT_DATE=$(git log -1 --format=%ad --date=iso-strict ${GITHUB_REF#refs/tags/})" > $GITHUB_ENV
          sed -i '' "s;MARKETING_VERSION = .*;MARKETING_VERSION = $(git describe --tags --abbrev=0 --match '[0-9]*\.[0-9]*\.[0-9]*' --first-parent);g" App.xcconfig
          sed -i '' "s;PRODUCT_VERSION = .*;PRODUCT_VERSION = $(git rev-list --count HEAD);g" App.xcconfig

      - name: Assemble Swift Source Release
        run: |
          # create the source zip file with predictable timestamps for reproducibility
          find . -exec touch -d "${COMMIT_DATE:0:19}" {} \;
          mkdir -p Packages/Skip/artifacts/
          zip -r Packages/Skip/artifacts/App-Source.zip . -x "Packages/*" -x ".git/*" -x ".build/*"

      - name: Run Tests
        run: swift test || swift test || swift test

      - name: Build ipa
        run: |
          mkdir -p Packages/Skip/artifacts
          APPARTIFACT="App"
          for CONFIGURATION in "Debug" "Release"; do
            ARCHIVE_PATH=".build/Skip/artifacts/${CONFIGURATION}/${APPARTIFACT}.xcarchive"
            BUILT_PRODUCTS_DIR=".build" xcodebuild -derivedDataPath .build/DerivedData -skipPackagePluginValidation -archivePath "${ARCHIVE_PATH}" -configuration "${CONFIGURATION}" -scheme "App" -sdk "iphoneos" -destination "generic/platform=iOS" -jobs 1 archive CODE_SIGNING_ALLOWED=NO
            cd "${ARCHIVE_PATH}"/Products/
            find . -type f
            mv "Applications" "Payload"
            # create zip file with reproducible timestamps
            find "Payload" -exec touch -t 197001010000 {} \;
            ditto -c -k --sequesterRsrc --keepParent "Payload" "${APPARTIFACT}-${CONFIGURATION}.ipa"

            cd -
            cp -av "${ARCHIVE_PATH}/Products/${APPARTIFACT}-${CONFIGURATION}.ipa" Packages/Skip/artifacts/
          done

      - name: Build apk
        run: |
          for CONFIGURATION in "Release" "Debug"; do
            for APPTARGET in "AppModelKt" "AppUIKt" "AppDroid"; do
              BUILT_PRODUCTS_DIR=".build" xcodebuild -derivedDataPath .build/DerivedData -skipPackagePluginValidation -configuration "${CONFIGURATION}" -destination "platform=macosx" -scheme "${APPTARGET}" -jobs 1 build CODE_SIGNING_ALLOWED=NO
            done
          done

      - name: Assemble Kotlin Source Release
        run: |
          #cd Packages/Skip/skipapp.output/AppUIKt/skip-transpiler/
          #cd ~/Library/Developer/Xcode/DerivedData/*/SourcePackages/plugins/skipapp.output/AppUIKt/skip-transpiler/
          cd .build/DerivedData/SourcePackages/plugins/skipapp.output/AppUIKt/skip-transpiler/
          rm -rf .gradle .build */.build
          # create the zip file with predictable timestamps for reproducibility
          find . -exec touch -d "${COMMIT_DATE:0:19}" {} \;
          zip -r ${OLDPWD}/Packages/Skip/artifacts/App-android-source.zip . -x ".build/*" -x "*/.gradle/*" -x "*/.build/*" -x "*/build/*"

      - name: "Release"
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Creating release: ${TAG}"
          cd Packages/Skip/artifacts/

          ls -la 

          APPNAME="App"
          # fix artifact names for release (retain App-Source.zip for template)
          cp -v App-Source.zip skip-template-source.zip
          cp -v App-Source.zip ${APPNAME}-ios-${TAG}-source.zip
          mv -v AppUI-release.apk ${APPNAME}-android-${TAG}.apk
          mv -v AppUI-debug.apk ${APPNAME}-android-${TAG}-debug.apk
          mv -v App-Release.ipa ${APPNAME}-ios-${TAG}.ipa
          mv -v App-Debug.ipa ${APPNAME}-ios-${TAG}-debug.ipa
          mv -v App-android-source.zip ${APPNAME}-android-${TAG}-source.zip

          shasum -a 256 *.* > checksums.txt

          cat > .relnotes << EOF
          These are the checksums for the release artifacts:
          EOF
          echo '```' >> .relnotes
          cat checksums.txt >> .relnotes
          echo '```' >> .relnotes

          gh release create "${TAG}" -t "Release ${TAG}" -F .relnotes *.*

      - name: "Upload Build Artifacts"
        # upload the artifacts generated from each build
        uses: actions/upload-artifact@v3
        if: always()
        with: 
          path: Packages/Skip/artifacts/

