name: "Skip Framework CI"
on:
  workflow_call:
    inputs:
      brew-install:
        required: false
        type: string

jobs:
  skip-framework:
    runs-on: macos-13
    timeout-minutes: 45
    env:     
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
    steps:
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: release-candidate

      - run: brew install skiptools/skip/skip tree ${{ inputs.brew-install }}

      - run: java -version

      - run: skip doctor

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Verify Skip Framework
        run: skip verify

      - name: Test iOS (connected)
        run: |
          # run the tests against the first listed scheme, which for a
          # single-module package will just be "project-name",
          # and for a multi-module package will be "project-name-Package"
          SKIP_ZERO=1 xcodebuild test -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15" -skipPackagePluginValidation -configuration debug -scheme $(xcodebuild -list -json | jq -r '.workspace.schemes[0]')

      - name: Test macOS & Robolectric (local)
        run: skip test --verbose

      - name: Prepare Android emulator
        run: |
          PACKAGE=$(swift package dump-package | jq -r '.name')
          MODULE=$(swift package dump-package | jq -r '.targets[] | select(.type == "test") | .name' | head -n 1)

          cd .build/
          ln -vs plugins/outputs/${PACKAGE}/${MODULE}/skipstone android-tests
          cd android-tests/
          # ensure we can write to the foldr
          chmod -Rf +w .
          # create the "gradlew" wrapper if it does not already exist
          gradle wrapper

      - name: Cache Android emulator snapshot
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-30-aosp-atd

      - name: Generate Android emulator snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: .build/android-tests
          target: aosp_atd
          api-level: 30
          arch: x86
          channel: canary
          profile: pixel
          avd-name: Pixel_3a_API_30
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching"


      - name: Test Android (connected)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: .build/android-tests
          target: aosp_atd
          api-level: 30
          arch: x86
          channel: canary
          profile: pixel
          #profile: Galaxy Nexus
          avd-name: Pixel_3a_API_30
          script: adb logcat *:S TestRunner:V & ./gradlew connectedCheck --stacktrace

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # extract package and initial module name from Package.swift
          PACKAGE=$(swift package dump-package | jq -r '.name')
          test -n "${PACKAGE}"
          MODULE=$(swift package dump-package | jq -r '.targets[0].name')
          test -n "${MODULE}"
          COMMIT_DATE=$(git log -1 --format=%ad --date=iso-strict ${GITHUB_REF#refs/tags/})
          test -n "${COMMIT_DATE}"

          # the tag is the most recent GitHub ref
          TAG="${GITHUB_REF#refs/tags/}"
          test -n "${TAG}"

          gradle assemble --project-dir .build/plugins/outputs/${PACKAGE}/${MODULE}Tests/skipstone -PbuildDir=.build/${MODULE}

          echo "Creating release: ${TAG}"
          mkdir -p Skip/build/artifacts/
          PKGDIR="../../../../../../Skip/build/artifacts/"

          tree ./.build/plugins/outputs/

          # create the release .aar
          cd ./.build/plugins/outputs/${PACKAGE}/${MODULE}Tests/skipstone
          cp -a ${MODULE}/.build/${MODULE}/outputs/aar/${MODULE}-release.aar ${PKGDIR}/${PACKAGE}-${TAG}.aar
          # copy the license for the source jar
          cp ../../../../../../LICENSE* .

          # create a source .jar distribution with consistent timestamps
          find . -exec touch -d "${COMMIT_DATE:0:19}" {} \;

          zip -r ${PKGDIR}/${PACKAGE}-${TAG}-sources.jar . -x '.*' -x 'build/*' -x '*/build' -x '*/build/*' -x '.*/*' -x '*/.*/*'

          # create a release with the assets and a checksums.txt file
          cd ${PKGDIR}
          shasum -a 256 *.* > checksums.txt
          gh release create "${TAG}" -t "Release ${TAG}" --generate-notes *.*
          #echo 'Release artifact SHA-256 hashes:' >> .relnotes
          #echo '```' >> .relnotes
          #cat checksums.txt >> .relnotes
          #echo '```' >> .relnotes
          #gh release create "${TAG}" -t "Release ${TAG}" -F .relnotes *.*

